title: HeartRockowanie 2020
name: Walentynki na rockowo
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # development
# url: "http://heartrockowanie.pl" # production
# url: "https://dwoznicka.github.io/heartrockowanie/" # staging

copyright: 2019 © <a href="https://heartrockowanie.pl" class="site-link">HeartRockowanie</a>. Wszelkie prawa zastrzeżone.
copyright_short: 2019 © <a href="https://heartrockowanie.pl" class="site-link">HeartRockowanie</a>.
made_by: 'Made with ❤ by DW'
# Build settings
markdown: kramdown
incremental: true
gems:
  - jekyll-watch
  - jekyll-assets
exclude:
- CNAME
- .gitignore
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor
- .ruby-version
- Guardfile
- .jekyll-assets-cache
- .sass-cache
- .editorconfig
- .idea
- .ruby-version
- .asset-cache
- _docs

#
# Plugin: jekyll-assets
#
assets:
  cache: false
  features:
    automatic_img_size: false
    automatic_img_alt: false
